ipAddr: 192.168.56.10
spring:
  datasource:
    username: root
    password: test
    url: jdbc:mysql://localhost:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&useInformationSchema=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-ware
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: ${ipAddr}
    port: 5672
    # 指定虚拟主机
    virtual-host: /
    username: guest
    password: guest
    # 开启发送端确认
    #publisher-confirms: true
    #x新版本配置
    publisher-confirm-type: correlated
    #　开启发送端消息抵达队列确认
    publisher-returns: true
    # 只要抵达队列，以异步优先回调我们这个 returnconfirm
    template:
      mandatory: true
    # 手动ack消息 消息不容易丢失
    listener:
      simple:
        acknowledge-mode: manual

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 11000
logging:
  level:
    com.atguigu.gulimall: debug
